version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: schedulerDB
    environment:
      MYSQL_ROOT_PASSWORD: 7-7dLhy75^%C
      MYSQL_DATABASE: schedules
      MYSQL_USER: scheduler_application
      MYSQL_PASSWORD: Gz44Lg]3£3WZ
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge